before myexception
MyException(MY EXECPT!)
MY EXECPT!
myexception catched
